# Generated by Django 5.1.4 on 2024-12-23 12:27

import core.models
import core.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.CharField(default=core.utils.random_id, editable=False, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(default=core.utils.random_id, editable=False, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('duration', models.TimeField()),
                ('release_date', models.DateField()),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='core.director')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to=core.utils.get_path, validators=[core.utils.image_size_validator])),
                ('bio', models.TextField(blank=True, max_length=256, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.CharField(default=core.utils.random_id, editable=False, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('movies', models.ManyToManyField(blank=True, related_name='movies', to='core.movie')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='core.profile')),
            ],
            options={
                'verbose_name': 'MovieList',
                'verbose_name_plural': 'MovieLists',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movielist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.movielist')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(default=core.utils.random_id, editable=False, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('user_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('content', models.TextField(max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=models.SET(core.models.get_deleted_user_instance), related_name='reviews', to='core.profile')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.movie')),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('movies', models.ManyToManyField(blank=True, related_name='watchlists', to='core.movie')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='core.profile')),
            ],
        ),
    ]
